# 이 YAML 파일은 포드 어피니티(Pod Affinity)를 사용하여 특정 포드와
# 동일한 노드에 스케줄링되도록 강제하는 예제입니다.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-podaffinity-hostname
spec:
  affinity:
    podAffinity:
      # 'requiredDuringSchedulingIgnoredDuringExecution'은 스케줄링 시점에 규칙을 반드시 만족해야 함을 의미합니다.
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          # 'mylabel/database' 레이블의 값이 'mysql'인 포드를 찾습니다.
          - key: mylabel/database
            operator: In
            values:
            - mysql
        # 'topologyKey'를 'kubernetes.io/hostname'으로 설정하여 동일한 노드를 의미하도록 합니다.
        # 즉, 'mysql' 포드가 실행 중인 바로 그 노드에 이 포드를 스케줄링합니다.
        topologyKey: kubernetes.io/hostname
  containers:
  - name: nginx
    image: nginx:latest