apiVersion: v1
kind: Pod
metadata:
  name: my-pod-required-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In  # 'In' 연산자 사용
            values:
            - ssd
            - hdd
  containers:
  - name: nginx
    image: nginx