apiVersion: v1
kind: Pod
metadata:
  name: my-app-replica-1
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: my-app  # 'app: my-app' 레이블을 가진 파드를 찾음
        topologyKey: kubernetes.io/hostname # 동일한 노드 내에서 찾음
  containers:
  - name: my-app
    image: my-app-image