# api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: masungil/fastapi-item-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mariadb-galera
            - name: DB_USER
              value: kosa
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-galera
                  key: mariadb-password
            - name: DB_NAME
              value: kosa_db
