apiVersion: v1
kind: Pod
metadata:
  name: my-team-a-app
spec:
  containers:
  - name: my-app
    image: nginx
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "team-a"
    effect: "NoSchedule"