apiVersion: v1
kind: Pod
metadata:
  name: tolerate-all-taints
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
  tolerations:
  - operator: "Exists" # key와 effect를 명시하지 않으면 모든 키와 모든 효과의 테인트를 허용합니다.