# 이 YAML 파일은 ResourceQuota 객체를 정의합니다.
# 이 할당량은 네임스페이스 전체의 컴퓨팅 리소스(CPU, 메모리) 사용량과
# 객체(Pod, Service)의 개수를 포괄적으로 제한합니다.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-example
  # 이 할당량은 'default' 네임스페이스에 적용됩니다.
  namespace: default
spec:
  # hard는 네임스페이스 전체에 대한 하드 리밋(절대 한도)을 설정합니다.
  hard:
    # 컴퓨팅 리소스 할당량
    # 네임스페이스 내 모든 Pod의 requests.cpu 합계는 1 코어를 초과할 수 없습니다.
    requests.cpu: "1000m"
    # 네임스페이스 내 모든 Pod의 requests.memory 합계는 500Mi를 초과할 수 없습니다.
    requests.memory: "500Mi"
    # 네임스페이스 내 모든 Pod의 limits.cpu 합계는 1.5 코어를 초과할 수 없습니다.
    limits.cpu: "1500m"
    # 네임스페이스 내 모든 Pod의 limits.memory 합계는 1000Mi(1Gi)를 초과할 수 없습니다.
    limits.memory: "1000Mi"

    # 객체 개수 할당량
    # 네임스페이스 내에 생성할 수 있는 Pod의 최대 개수는 3개입니다.
    count/pods: "3"
    # 네임스페이스 내에 생성할 수 있는 Service의 최대 개수는 5개입니다.
    count/services: "5"