apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: calculator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calculator-deployment # 타겟 디플로이먼트
  minReplicas: 1  # 최소 복제본 수
  maxReplicas: 10 # 최대 복제본 수
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # CPU 사용률 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 # 메모리 사용률 80%
