apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-cnf-configmap
data:
  # 로그 생성 및 유지 설정 / server-id 부여
  master.cnf: |
    [mysqld]
    log-bin = mysql-bin 
    server-id = 1 
    binlog_format = row 
    expire_logs_days = 2

  # 서버 아이디 부여
  slave.cnf: |
    [mysqld]
    server-id = ${SERVER_ID}
    relay-log=relay-bin
    read_only=ON
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-sql-configmap
data:
  # DB 계정 생성 및 테이블 정의
  01-common.sql: |
    CREATE DATABASE IF NOT EXISTS kosa_db;
    CREATE USER 'kosa'@'%' IDENTIFIED BY '1004';
    GRANT ALL PRIVILEGES ON kosa_db.* TO 'kosa'@'%';  -- Todo: 아이디 비번 하드코딩됨. 나중에 init-conainter에서 주입하는 방식 ㄱㄱ
    GRANT SELECT ON mysql.* TO 'kosa'@'%';

    -- 예제 테이블
    CREATE TABLE IF NOT EXISTS kosa_db.items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL
    ) ENGINE=InnoDB;

  # master에서 dump담당 계정 생성 및 권한부여 / slave에서 이용 예정
  02-master.sql: |
    -- Create a replication user
    CREATE USER 'repl_user'@'%' IDENTIFIED BY 'repl';  -- Todo: 아이디 비번 하드코딩됨. 나중에 init-conainter에서 주입하는 방식 ㄱㄱ

    -- Grant replication slave privilege to the replication user
    GRANT REPLICATION SLAVE ON *.* TO 'repl_user'@'%';
    FLUSH PRIVILEGES;

  # 슬레이브에 마스터 등록 template / init-conatiner에서 master정보 입력 예정
  02-slave.sql: |
    STOP SLAVE;
    CHANGE MASTER TO
    MASTER_HOST= 'mariadb-0.mariadb-headless',
    MASTER_USER= 'repl_user', -- Todo: 아이디 하드코딩 나중에 바꾸기
    MASTER_PASSWORD= 'repl', -- Todo: 비밀번호 하드코딩 나중에 바꾸기
    MASTER_LOG_FILE= '${LOG_FILE}',
    MASTER_LOG_POS= ${LOG_POS},
    MASTER_SSL=0;
    START SLAVE;

    
        
