apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      name: mariadb
  clusterIP: None # Headless Service
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  labels:
    app: mariadb
    role: master
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mariadb
  selector:
    app: mariadb
    apps.kubernetes.io/pod-index: "0"
