# 이 YAML 파일은 쿠버네티스 디플로이먼트(Deployment)의 초기 버전을 정의합니다.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # nginx 1.15 버전 이미지를 사용합니다.
        image: nginx:1.15
        ports:
        - containerPort: 80