# 이 YAML 파일은 Readiness Probe를 사용하는 파드와 이를 노출하는 서비스를 정의합니다.
apiVersion: v1
kind: Pod
metadata:
  name: readinessprobe-pod
  labels:
    my-readinessprobe: test
spec:
  containers:
  - name: readinessprobe-pod
    image: nginx
    # readinessProbe는 컨테이너가 요청을 처리할 준비가 되었는지 확인합니다.
    readinessProbe:
      httpGet:
        port: 80
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: readinessprobe-svc
spec:
  ports:
    - name: nginx
      port: 80
      targetPort: 80
  # selector는 이 서비스가 트래픽을 전달할 파드를 선택합니다.
  # "my-readinessprobe: test" 레이블을 가진 파드를 대상으로 합니다.
  # readinessProbe 검사에 실패한 파드는 이 서비스의 엔드포인트에서 제외됩니다.
  selector:
    my-readinessprobe: test
  type: ClusterIP