# --- Service --- #
apiVersion: v1 # Service는 핵심(core) API 그룹에 속하므로 v1을 사용합니다.
kind: Service # 리소스의 종류는 'Service' 입니다.
metadata:
  name: php-apache # 이 Service의 고유한 이름
# spec: Service의 상세 스펙을 정의합니다.
spec:
  # selector: 이 Service가 트래픽을 전달할 대상 파드를 선택합니다.
  # 아래 레이블을 가진 파드들이 이 Service의 대상이 됩니다. (deployment.yaml의 파드 레이블과 일치해야 함)
  selector:
    app: php-apache
  # ports: 서비스가 노출할 포트를 정의합니다.
  ports:
  - protocol: TCP # 사용할 프로토콜
    port: 80 # 서비스 자체가 노출될 포트
    # targetPort는 생략되었으며, 이 경우 자동으로 'port'와 동일한 값(80)으로 설정됩니다.
  # type: 서비스의 종류를 정의합니다.
  type: NodePort